---
title: "analytical_posterior"
output: html_document
---

---
title: "Single Site, Single Disturbance, MultiPool"
author: "Mike Dietze"
date: "10/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(BayesianTools)
library(magrittr)
set.seed(42)
```

## Todo

-   Tweak model to have a simple C budget -- where does the C go when the model doesn't assimilate disturbance?

## helper functions

```{r}
source("multi.ens.adj.R")

## set values of state less than zero to be 0 
tobit <- function(x){
  x[x < 0] <- 0
  x
}

### Constants to be used for disturbance function
mu0 <- c(1,1)                   ## mean leaf & stem biomass after disturbance
V0  <- diag(c(0.15,0.25))^2     ## var in post disturbance leaf and stem biomass
alloc.soil = 0.25        ## fraction of removed C that goes in the soil
  
## parameters: x = (Cleaf, Csoil, Cstem) biomass amounts
## returns: x with disturbance applied. Subtract from all values, with the soil 
##          preserving some of the removed biomass
disturbance <- function(x){ ## x = (Cleaf, Csoil, Cstem)
  biomass_idxs <- c(1, 3)
  soil_idx <- 2
  old.biomass <- x[biomass_idxs]
  new.biomass <- tobit(mvtnorm::rmvnorm(1,mu0,V0)) ## draw disturbed leaf and stem
  check.max <- which(new.biomass > old.biomass)
  if(length(check.max)>0) new.biomass[check.max] = old.biomass[check.max] ## biomass can only decrease after disturbance
  residual = sum(old.biomass-new.biomass)
  x[biomass_idxs] <- new.biomass
  x[soil_idx] <- x[soil_idx] + residual*alloc.soil ## soil gets some biomass
  removal <- residual*(1-alloc.soil)
  return(x)
}

```

## drivers

```{r}
NYears = 25 # 25 year burn-in
ndays = 365*NYears # final timestep / total number of days
time = 1:ndays 
ndrivers   = 31 ## number of driver ensembles
PAR_driverdata <- matrix(NA,ndrivers,ndays) # [ndrivers = number of drivers x ndays = total number of days], PAR = Photosynthetic active radiation
for(i in 1:ndrivers){
  PAR_driverdata[i,] <- VSEMcreatePAR(time)  
}
plot(PAR_driverdata[1,], main = "PAR (driving the model)", xlab = "Day",cex=0.35)
```

## Parameters

```{r}
refPars <- VSEMgetDefaults() # VSEM reference params
refParStateIndices <- 9:11 # indices of cleaf, csoil, and cstem amounts in full VSEM params obj
refPars$lower[refParStateIndices] = 1
nparamsamples = 50 # number of samples of model parameters
sigmaP = diag((refPars$upper - refPars$lower)/10)^2 ## assume range is +/- 5 SD
Theta_reference <- as.data.frame(mvtnorm::rmvnorm(nparamsamples,refPars$best,sigmaP)) # Theta_reference = [50 (# param samples) x 11 (# state variables)], param samples of \theta (reference parameters with added noise)
colnames(Theta_reference) <- rownames(refPars)
par(mfrow=c(3,4))
for(i in 1:11){ # fix theta values within lower and upper bounds of the ref pars
  Theta_reference[Theta_reference[,i] < refPars$lower[i] , i] <- refPars$lower[i]
  Theta_reference[Theta_reference[,i] > refPars$upper[i] , i] <- refPars$upper[i]
  hist(Theta_reference[,i],main=colnames(Theta_reference)[i])
}
```

## initial conditions

```{r}
## spin up
n_ensemble_members = 200 # number of ensemble members
met = sample.int(ndrivers,n_ensemble_members,replace=TRUE)  # [1 x n_ensemble_members = number of ensemble members] met / forcing / driver data index for each ensemble member
par = sample.int(nparamsamples,n_ensemble_members,replace=TRUE)  # [1 x n_ensemble_members] parameter indices for each ensemble member
Ensemble_initial <- matrix(NA,n_ensemble_members,3) # [n_ensemble_members x 3 = (Cleaf, Csoil, Cstem)] initial ensemble of (Cleaf, Csoil, Cstem) states 
vsem_state_indices <- 2:4 # indices of Cv, Cs, Cr values in VSEM outputs
for(i in 1:n_ensemble_members){
  # Run VSEM with paramter indices / met data
  # get Cleaf/Csoil/Cstem values at final timestep (after 25 years)
  # store in Ensemble_initial
  Ensemble_initial[i,] = VSEM(as.numeric(Theta_reference[par[i],]),PAR = PAR_driverdata[met[i],])[ndays,vsem_state_indices] 
}
Ensemble_initial.orig = Ensemble_initial
Ensemble_means = Ensemble_means_kalman = Forecast_means_kalman = Forecast_means = Ensemble_initial*NA
par(mfrow=c(1,3))
hist(Ensemble_initial[,1],main="Cleaf")
hist(Ensemble_initial[,2],main="Csoil")
hist(Ensemble_initial[,3],main="Cstem")
```

## set up storage and parameters

```{r}
## hard coded 
Q = diag(c(0.1,0.1,0.1)) ## process error
R = diag(c(.25,10,1))      ## observation error
THETA <- as.matrix(Theta_reference[par,]) ## initial ensemble parameters [J, P]
p.dist = 0.05

## storage
Analysis <- Forecast <- list()
Forecast.KD = Analysis.KD = list() ## EnKF with Disturbance

## pseudodata
Observed_states = matrix(NA,NYears,3)                   ## storage for observed state
True_states = matrix(NA,NYears,3)                ## storage for latent "true" state
ref_idx = 42                              ## reference ensemble member
disturbance_at = rep(0,NYears)                     ## true disturbance timeseries
disturbance_at[10] = 1                         ## prescribe a disturbance
refpar = as.numeric(Theta_reference[par[ref_idx],]) ## grab the "true" parameters
refpar[refParStateIndices] = Ensemble_initial[ref_idx,]               ## set initial biomass pools
for(year in 1:NYears){
  sel_days <- (year-1)*365 + 1:365            ## select 1 yr of met  
  simulated_state = VSEM(refpar,PAR_driverdata[met[ref_idx],sel_days])[365,vsem_state_indices]    ## forward simulation
  state_with_process_error  = mvtnorm::rmvnorm(1,simulated_state,Q)## process error
  if(disturbance_at[year]){
    state_with_process_error = disturbance(state_with_process_error)
  }
  state_with_process_error = tobit(state_with_process_error)
  refpar[9:11] = state_with_process_error                 ## update IC for next iteration
  True_states[year,] = state_with_process_error ## store true observation
  Observed_states[year,] = tobit(mvtnorm::rmvnorm(1,state_with_process_error,R)) ## store observation with error
}
par(mfrow=c(3,1))
plot(Observed_states[,1])
plot(Observed_states[,2])
plot(Observed_states[,3])
```

```{r echo=FALSE, message=FALSE, results='hide'}

AnalysisSSSDMP <- "  ## SingleSite SingleDisturbance MultiPool
model{
  ## prior
  muN ~ dmnorm(mufN,pfN)                ## forecast prior on Not disturbed
  muD ~ dmnorm(mufD,pfD)                ## forecast prior on Disturbed
  D ~ dbern(p)                          ## disturbance probability
  ## Analysis 
  n <- D*muD + (1-D)*muN                ## select between disturbed and undisturbed
  Y ~ dmnorm(n,R)                       ## Observation error
}"

Ensemble_initial <- Ensemble_initial_kalman <- Ensemble_initial.orig
THETA_Kalman <- THETA # stored states for experiment without pure ensemble Kalman Filter
for(t in 1:NYears){
  
  tsel <- (t-1)*365 + 1:365               ## Select days from driver files
  
  ## update IC
  THETA[,9:11]  <- Ensemble_initial    ## Multinomial [n_ensemble_members x 3 = num state variables]
  THETA_Kalman[,9:11] <- Ensemble_initial_kalman  ## EnKF w/ disturbance [n_ensemble_members x 3 = num state variables]
  
  ## Forecast 
  for(i in 1:n_ensemble_members){
    fx       = VSEM(THETA[i,], PAR = PAR_driverdata[met[i],tsel]) ## deterministic simulation
    Ensemble_means[i,]  =  fx[365,vsem_state_indices]                         ## state variables at time of assim
    fxK      = VSEM(THETA_Kalman[i,],PAR = PAR_driverdata[met[i],tsel]) ## deterministic simulation
    Ensemble_means_kalman[i,] = fxK[365,vsem_state_indices] ## deterministic simulation
    epsilon  = mvtnorm::rmvnorm(1,rep(0,3),Q)                   ## process error  ** shared between versions **
    Forecast_means[i,]   = Ensemble_means[i,]  + epsilon
    Forecast_means_kalman[i,]  = Ensemble_means_kalman[i,] + epsilon
  }
  
  ## Disturbance
  d.prior <- rbinom(n_ensemble_members,1,p.dist)             ## (1 x ne) prior on disturbance status, 0=no disturbance, 1=disturbance
  sel <- !as.logical(d.prior)                ## select undisturbed ensemble members
  if(sum(!sel)>2){
    sel.dist = which(!sel) # find indices of disturbed ensemble members
    for(j in sel.dist){                      ## run disturbance model, update disturbed ensemble states
      Forecast_means[j,]  = disturbance(Forecast_means[j,])
      Forecast_means_kalman[j,] = disturbance(Forecast_means_kalman[j,])
    }
    mufD  = colMeans(Forecast_means[!sel,])
    pfD = solve(diag(c(0.15,0.5,0.25)^2)) #try(solve(var(Nf[!sel,]))) # invert this diagonal matrix
  } 

  if(sum(!sel) <= 2 || "try-error" %in% class(pfD)) {   ## backup values if the ensemble stats fail
    mufD = c(mu0[1], mean(Forecast_means[,2]),  mu0[2])            
    pfD  = solve(diag(c(0.15,0.5,0.25)^2))
  }
  Forecast_means <- tobit(Forecast_means)
  
  ## EnKF forecast stats
  Forecast_means_kalman <- tobit(Forecast_means_kalman)
  mufK = colMeans(Forecast_means_kalman)
  PfK  = var(Forecast_means_kalman)
  pfK  = solve(PfK)             ## Not disturbed forecast precision (inverse of covariance PfK)
  Forecast.KD[[t]] <- list(d.prior=d.prior,Forecast_means=Forecast_means_kalman,muf=mufK,pf=pfK)

  ## priors
  priors <- list(p    = mean(d.prior),         ## disturbance rate (approximation of p.dist)
                 mufN = colMeans(Forecast_means[sel,]),    ## Not disturbed forecast means
                 mufD = mufD,   ## Disturbed forecast means
                 pfN  = solve(var(Forecast_means[sel,])),  ## Not disturbed forecast precision
                 pfD  = pfD  ## Disturbed forecast precision
  )
  Forecast[[t]] <- c(list(d.prior=d.prior,Nf=Forecast_means),priors)
  
  ## Analysis
  update = c(list(Y=Observed_states[t,],R=solve(R)),priors)
  mod <- rjags::jags.model(file=textConnection(AnalysisSSSDMP),
                           data=update,
                           n.adapt=2000,n.chains=10)
  jdat <- rjags::coda.samples(mod,variable.names=c("n","D","muN","muD"),n.iter=10000) 
  
  ## update parameters & save Analysis posterior
  dat = as.matrix(jdat)
  nsel <- grep(pattern="^n",x=colnames(dat))
  
  if (t == 9) {
     jdat10 <- jdat 
  }
  
  ## draw new IC
  Ensemble_initial <- multi.ens.adj(
          Xf   = Forecast_means,
          cf   = d.prior,
          mu.f = rbind(priors$mufN,priors$mufD),
          Pf   = abind::abind(solve(priors$pfN),
                 solve(priors$pfD),
                 along=3),  # covariance matrices for undisturbed / disturbed ensemble states
          Xa = dat[,nsel],
          ca = dat[,"D"])
  Ca <- Ensemble_initial[,1] ## updated class assignments (get prepended from call to multi.ens.adj)
  Ensemble_initial <- tobit(Ensemble_initial[,-1]) ## remove class assignments
#  sel.ic <- sample.int(nrow(dat), ne, replace=TRUE)
#  Na <- dat[sel.ic,nsel]
  Analysis[[t]] <- list(MCMC=dat,
                        Na = Ensemble_initial,
                        Ca = Ca)

  
  ## EnKF Analysis
  I = H <- diag(rep(1,3))
  K <- PfK %*% t(H) %*% solve(H%*%PfK%*%t(H) + R)
  muaK <- mufK + K%*%(Observed_states[t,] - mufK) 
  PaK <- (I-K %*% H)%*%PfK    
  paK = solve(PaK)
  Ensemble_initial_kalman <- PEcAnAssimSequential::adj.ens(Pf = PfK,X = Forecast_means_kalman,mu.f = mufK,mu.a = muaK,Pa = PaK) %>% as.matrix()
  Analysis.KD[[t]] <- list(mua=muaK,pa=paK,Pa=PaK,Na=Ensemble_initial_kalman)
  
}

```


### time series

```{r}
pool.names=c("Cleaf","Csoil","Cstem")
for(i in 1:3){
  
  CI.Na = sapply(X = Analysis,function(y){
    x = y$MCMC
    sel.n = which(colnames(x) == paste0("n[",i,"]"))
    quantile(x[,sel.n],c(0.025,0.5,0.975))
  })
  # CI.Na = sapply(X = Analysis,function(x){
  #  apply(x,2,quantile,c(0.025,0.975))
  # })
  
  plot(Observed_states[,i],
       #ylim = range(rbind(CIN,data$Y)),xlim=xlim,type='n',
       ylab=pool.names[i],xlab="time")
}
```


```{r}
library(mvtnorm)

#par(mfrow=c(1,2))

# print(jdat10)
# jdat10["n[1]"] <- as.numeric(as.character(jdat10["n[1]"]))
# jdat10["n[3]"] <- as.numeric(as.character(jdat10["n[3]"]))
# print(summary(jdat10[,"n[1]"]))
# # print(summary(jdat10[,"n[3]"]))
# print(as.matrix(jdat10[,'n[1]']))
t = 25
data <- Analysis[[t]]$MCMC
plot(as.matrix(data[,'n[1]']), as.matrix(data[,'n[3]']),
     pch = 16,               # filled circles
     col = "blue",           # color
     xlab = "n[1]",
     ylab = "n[3]",
     main = "Scatter plot of n[1] vs n[3]")

hist(as.matrix(data[,"D"]), breaks = seq(-0.5, 1.5, by=1),
     main = "Histogram of Data",
     xlab = "Value",
     col = "skyblue",
     border = "white")

# compute not disturbed and disturbed forecast means / covariances at timestep t
mufN_t = Forecast[[t]]$mufN
mufD_t = Forecast[[t]]$mufD
PfN_t = solve(Forecast[[t]]$pfN)
PfD_t = solve(Forecast[[t]]$pfD)

# posterior means / covariances
post_PfN_t = solve(solve(PfN_t) + solve(R))
post_mufN_t = post_PfN_t%*%(solve(R)%*%Observed_states[t,] + solve(PfN_t)%*%mufN_t)
post_PfD_t = solve(solve(PfD_t) + solve(R))
post_mufD_t = post_PfD_t%*%(solve(R)%*%Observed_states[t,] + solve(PfD_t)%*%mufD_t)
w_N_t = dmvnorm(Observed_states[t,], mean=mufN_t, sigma=PfN_t + R)
w_D_t = dmvnorm(Observed_states[t,], mean=mufD_t, sigma=PfD_t + R)
w_N_t = w_N_t / (w_N_t + w_D_t)
w_D_t = w_D_t / (w_N_t + w_D_t)

# get samples from the posterior
n_samples <- 10000
# Mixture weights must sum to 1
weights <- c(w_N_t, w_D_t)
components <- sample(1:2, size = n_samples, replace = TRUE, prob = weights)
d <- length(post_mufN_t)  # dimensionality
samples <- matrix(NA, nrow = n_samples, ncol = d)
n_N <- sum(components == 1)
n_D <- sum(components == 2)
print(post_mufN_t)
print(post_PfN_t)
print(post_mufD_t)
print(post_PfD_t)
# print(rmvnorm(n = n_N, mean = as.numeric(post_mufN_t), sigma = as.matrix(post_PfN_t)))
if(n_N > 0) {
  samples[components == 1, ] <- rmvnorm(n = n_N, mean = post_mufN_t, sigma = post_PfN_t)
}
if (n_D > 0) {
  samples[components == 2, ] <- rmvnorm(n = n_D, mean = post_mufD_t, sigma = post_PfD_t)
}

# plot the samples
plot(samples[,1], samples[,2], 
     xlab = "X", ylab = "Y", 
     main = "Samples from Posterior Mixture", 
     pch = 19, col = rgb(0,0,1,0.5))

print("weights:")
print(weights)
print("posterior mu_N:")
print(post_mufN_t)
print("posterior PfN")
print(post_PfN_t)

nsel <- grep(pattern="^n",x=colnames(data))
dat_samples <- data[,nsel]
print("MCMC sample mean")
print(colMeans(dat_samples))
print("MCMC sample covariance")
print(var(dat_samples))
```

```{r}
ecoforecastR::ciEnvelope(1:ncol(CI.Na),CI.Na[1,],CI.Na[3,],col=ecoforecastR::col.alpha('#b2df8a',0.7))
  lines(CI.Na[2,],col="#b2df8a",lwd=2)
  lines(True_states[,i],lty=2,lwd=2)
}
```
### Ensemble adj at time of disturbance

```{r,fig.asp=1,fig.width=10}
#par(mfrow=c(1,3))

plot(Analysis[[10]]$Na[,1],Analysis[[10]]$Na[,3],pch="+",col=ecoforecastR::col.alpha("red",alpha=0.5),
     ylim=range(Forecast[[10]]$Nf[,3]),
     xlim=range(Forecast[[10]]$Nf[,1]),
     xlab=pool.names[1],ylab=pool.names[3],
     cex.lab=1.25,asp = 1)
points(Forecast[[10]]$Nf[,1],Forecast[[10]]$Nf[,3],cex=0.5)
points(Observed_states[10,1],Observed_states[10,3],cex=3,col=ecoforecastR::col.alpha("purple",alpha = 0.75),pch=18)

## ensemble adjustment
sel.a=sample.int(n_ensemble_members,10)
arrows(Forecast[[10]]$Nf[sel.a,1],Forecast[[10]]$Nf[sel.a,3],
       Analysis[[10]]$Na[sel.a,1],Analysis[[10]]$Na[sel.a,3],length = 0.1,lwd = 0.5)   
# legend("topleft",
#        legend=c("Forecast","Analysis","Data"),
#        pch=c(1,3,18),col=c(1,2,"purple"),
#        cex = 1.5)

```
## EnKF, no disturbance
```{r}
THETA[,9:11] <- Ensemble_initial.orig
print(THETA[1,])
```


```{r,echo=FALSE}
Ensemble_initial <- Ensemble_initial.orig
Forecast.EnKF = Analysis.EnKF = list()
for(t in 1:NYears){
  
  tsel <- (t-1)*365 + 1:365               ## Select days from driver files
  
  ## update IC
  # print(THETA[0,])
  THETA[,9:11]  <- Ensemble_initial
  
  ## Forecast 
  for(i in 1:n_ensemble_members){
    Ensemble_means[i,] = VSEM(THETA[i,],PAR = PAR_driverdata[met[i],tsel])[365,2:4] ## deterministic simulation
    Forecast_means[i,]  = mvtnorm::rmvnorm(1,Ensemble_means[i,],Q) ## process error
  }
  
  muf = colMeans(Forecast_means)    ## Not disturbed forecast means
  Pf  = var(Forecast_means)
  pf  = solve(Pf)             ## Not disturbed forecast precision
  Forecast.EnKF[[t]] <- list(d.prior=d.prior,Nf=Forecast_means,muf=muf,pf=pf)
  
  ## Analysis
  I = H <- diag(rep(1,3))
  K <- Pf %*% t(H) %*% solve(H%*%Pf%*%t(H) + R)
  mua <- muf + K%*%(Observed_states[t,] - muf) 
  Pa <- (I-K %*% H)%*%Pf    
  pa = solve(Pa)
  
  ## draw new IC
  #  Na <- mvtnorm::rmvnorm(ne,mua,Pa)
  Ensemble_initial <- as.matrix(PEcAnAssimSequential::adj.ens(
  Pf = Pf,X = Forecast_means,mu.f = muf,mu.a = mua,Pa = Pa))
  ## save Analysis posterior
  Analysis.EnKF[[t]] <- list(mua=mua,pa=pa,Pa=Pa,Na=Ensemble_initial)

}



```
